apiVersion: v1
kind: kustomization
metadata:
  name: testnamespace-flux-kustomization
spec:
  path: ./overlays/prod/aws/east/account_name
  sourceRef:
     kind: GitRepository
     name: New-Repo-Name-sync
----------------

apiVersion: v2
kind: GitRepository
metadata:
  name: New-Repo-Name
spec:
  url: "ssh://git@github.com:vinayreddy05/{new_repo_name}.git"


