apiVersion: v1
kind: kustomization
metadata:
  name: {{ namespace }}-flux-kustomization
spec:
  path: ./overlays/prod/aws/east/account_name
  sourceRef:
     kind: GitRepository
     name: {{ new_repo_name }}-sync
----------------

apiVersion: v2
kind: GitRepository
metadata:
  name: {{ new_repo_name }}
spec:
  url: "ssh://git@github.com:vinayreddy05/{new_repo_name}.git"


